# Prose edits for paper/sage_sa.tex that the stage 5 core requires: the model
# now carries an i.i.d. logit taste shock, the proposition is its theta -> 0
# limit, and the numerics paragraphs describe the new footing. Dry-run unless
# --apply. Run AFTER stage5_paper_subs.py.
import sys
from pathlib import Path
import re
S = Path("SAGE_Bewley/scripts")
THETA = float(re.search(r"const THETA *= *([0-9.]+)", (S/"sa_level4.jl").read_text()).group(1))
KAPPA = float(re.search(r"const KAPPA *= *([0-9.]+)", (S/"sa_level4.jl").read_text()).group(1))
SIGMA = float(re.search(r"const SIGMA *= *([0-9.]+)", (S/"sa_level4.jl").read_text()).group(1))
# theta limit at the final point: rows "kappa* .. | rate r .. | slope s .." at theta 0.005 and 0.0025
lb = (S/"sa_recalibrate_l5b.txt").read_text()
rows = re.findall(r"rate ([0-9.]+) groups .*?\| slope ([0-9.]+) mult", lb)
r_t5, s_t5 = float(rows[0][0]), float(rows[0][1]); r_t25, s_t25 = float(rows[1][0]), float(rows[1][1])
na4 = re.search(r"na=400: rate ([0-9.]+) slope ([0-9.]+)\s+\(na=200: rate ([0-9.]+)", lb)
r_na400, r_na200 = float(na4.group(1)), float(na4.group(3))
# audit identity (may not exist yet at the final point)
au = (S/"audit_sa.txt").read_text() if (S/"audit_sa.txt").exists() else ""
a1 = re.findall(r"^0\.01 +\| +[-0-9.]+ +\| +[-0-9.]+ +\| +([0-9.]+) +\| +([0-9.]+) +\| +([-+0-9.]+)%", au, re.M)
ident = f"the measured multiplier is {float(a1[0][0]):.3f} against a predicted {float(a1[0][1]):.3f}, a gap of {abs(float(a1[0][2])):.1f} percent" if a1 else "IDENTITY_PENDING"
# valley
vf = S/"sa_valley.txt"
if not (vf.exists() and "DONE" in vf.read_text()):
    vf = S/"sa_valley_theta0.0100.txt"; print("NOTE: valley at theta 0.005 not finished; using the theta 0.01 trace for the dry run")
va = vf.read_text()
vrows = re.findall(r"^([0-9.]+) +([0-9.]+) +\| +([0-9.]+) +([0-9.]+) / ([0-9.]+) \| +([0-9.]+) +\| +([0-9.]+) +([0-9.]+) +\| +([0-9.]+) +([0-9.]+) +\|", va, re.M)
V = [(float(a),float(b),float(f),float(g),float(h),float(i),float(j)) for a,b,c,d,e,f,g,h,i,j in vrows]  # sigma,kappa,rtloss,slope,mult,sigbar,ratio
V50 = [v for v in V if abs(v[0]-0.50)<1e-6][0]; V100 = [v for v in V if abs(v[0]-1.00)<1e-6][0]
edits = [
# Section 2.3: the reduction paragraph gains the shock
("Computation exploits a reduction: within a group, the payoff depends on $(\\kappa, m, B_g, \\omega, r)$ only through one scalar, so each group's response is precomputed once on a grid of that scalar at production resolution, and every map evaluation, calibration loop, and policy counterfactual is interpolation.",
 "One more ingredient is needed before the model can be computed reliably, and it is the one \\citet{brock2001} start from: on top of the persistent taste $m$, each period the household draws an i.i.d. type-1 extreme-value shock to the participation payoff, with scale $\\theta$. The participation choice is then a logit probability rather than a step, and the hard-threshold model of the previous subsection is its $\\theta \\to 0$ limit. The shock is kept small, $\\theta = " + f"{THETA:g}" + "$, and Section 6.5 shows that every quantity reported has settled to within a fraction of a point of that limit; its role is to make the aggregate an integral of a smooth function over the wealth distribution rather than the mass above a cutoff, which is what the discretisation could not otherwise resolve. Computation then exploits a reduction: within a group, the payoff depends on $(\\kappa, m, B_g, \\omega, r)$ only through one scalar, so each group's response is precomputed once on a grid of that scalar at production resolution, and every map evaluation, calibration loop, and policy counterfactual is interpolation."),
# Section 3: numerical settings paragraph
("The response families are built on a grid concentrated at spacing $0.2$ across the transition interval, and the taste quadrature uses 2000 nodes; at those settings the calibrated equilibrium moves by 0.002 between 500 and 4000 nodes.",
 "The response families are built on a grid concentrated at spacing $0.2$ across the transition interval; the taste quadrature uses 2000 nodes, of which 500 would suffice once the choice is smoothed; and the asset grid is concentrated where the wealth distribution actually lives, which for the French calibration is below two years of income. At those settings the calibrated equilibrium is stable to $3 \\times 10^{-4}$ across a fourfold range of asset-grid sizes."),
# Section 5: after the proposition's proof paragraph, one sentence on the limit
("The proposition says something that is not evident before the algebra:",
 "The proposition is stated for the hard-threshold model, and the computed model of Section 2.3 carries a small logit shock; the two agree in the limit, and at the $\\theta$ used the map slope sits within " + f"{abs(s_t5-s_t25):.3f}" + " of its limiting value, so nothing below turns on the distinction. The proposition says something that is not evident before the algebra:"),
("Robustness statements throughout the paper use the country rows; the cross-country fit table is in the public repository.",
 "Robustness statements throughout the paper use the country rows; the cross-country fit table is in the public repository. One cross-country result is worth stating here because it is untargeted: the model's participation rate, computed for each country from its agency and belonging inputs alone, orders the six countries for which the WISE Recoupling Solidarity Index exists in the same way that index does, with a rank correlation between 0.46 and 0.94 across the index's three years and above 0.80 among the four OECD members, and it does so better than either input alone. The companion paper's cohesion object, all non-work time, ordered the same countries backwards."),
("Three readings, stated carefully.",
 "One more thing the calibration itself shows, and it explains why this margin is the number most exposed in the paper. The two participation moments do not identify a point in $(\\kappa, \\sigma_m)$ but a curve: tracing the best $\\kappa$ at each $\\sigma_m$, the moment loss has a definite minimum at $\\sigma_m = " + f"{V50[0]:.2f}" + "$ and rises steadily along the curve, doubling by $\\sigma_m = 0.75$ and reaching " + f"{V100[2]/V50[2]:.1f}" + " times the minimum at $1.0$. Along that whole curve the bound barely moves, from " + f"{min(v[5] for v in V if v[0]>=0.5):.3f}" + " to " + f"{max(v[5] for v in V):.3f}" + ", exactly as the proposition requires since it depends only on the group rates the moments pin. What the moments do not pin is $\\sigma_m$ itself, so the ratio runs from " + f"{V50[6]:.2f}" + " at the best fit to " + f"{V100[6]:.2f}" + " at the far end, and the policy multiplier of the next section, which is the same slope read the other way, runs from " + f"{V50[4]:.1f}" + " to " + f"{V100[4]:.1f}" + ". The verdict holds everywhere on the curve; the margin is a range, reported here at its best-fitting value. An earlier draft of this paper reported the margin at a point two thirds of the way along this curve, where the fit is twice as poor, because the numerics of the time could not resolve the low-dispersion end; the difference between the two drafts is entirely a move along this curve. Three readings, stated carefully."),
# Section 6.5: full rewrite
("The companion paper's central quantity, the public good $Q = \\mathbb{E}[1-e]$, is a mean of effort and inherits the resolution of the effort grid, which is why that paper reports the checks it does. The central quantity here is different: participation is a discrete choice, and the aggregate rate is a mass rather than an average of a finely graded object, so it should be far less sensitive. It is. Rebuilding the response families with the effort grid doubled and doubled again, the calibrated equilibrium moves from 0.35303 to 0.35305 to 0.35307 and the group rates move in the fifth decimal; mean labour income, which does inherit the effort grid, moves by at most three tenths of a percent, which is the accuracy to attach to the GDP column of Table \\ref{tab:gdpb}.",
 "Three checks carry the numbers in this paper, and each exists because something was once reported wrong. The first is an identity. For a small financed subsidy the equilibrium response must equal the direct response divided by $1 - G'(r^*)$, with no free parameter, so a numerical footing that fails it is wrong whatever else it reproduces. At a one percent subsidy " + ident + ", and the gap grows with the shock exactly as curvature says it should; the earlier footing of this paper missed the same test by 48 percent. The second is grid convergence. The participation rate moves by " + f"{abs(r_na400-r_na200):.3f}" + " across a doubling of the asset grid at a point where the multiplier is near ten, so that is the grid's contribution amplified tenfold, to the sixth decimal across the grid on which the aggregate map is traced, and to the fifth decimal across two doublings of the effort grid; mean labour income, which inherits the effort grid, moves by at most three tenths of a percent, which is the accuracy to attach to the GDP column of Table \\ref{tab:gdpb}. The third is the limit in $\\theta$. Halving the logit scale from the working value, the participation rate moves from " + f"{r_t5:.3f}" + " to " + f"{r_t25:.3f}" + " and the map slope from " + f"{s_t5:.3f}" + " to " + f"{s_t25:.3f}" + ", and the calibrated point itself is identical on both, so the results sit within " + f"{abs(r_t5-r_t25):.3f}" + " and " + f"{abs(s_t5-s_t25):.3f}" + " of the hard-threshold limit the proposition is stated for."),
("The sensitivity that does matter here is the one Section 3 describes, and it is worth being explicit about how much it cost. The response of a group to the belonging scale is close to a step function, so a grid spread evenly over the range puts almost no nodes where the response moves, and the integral of a near-step over the taste distribution converges slowly. An earlier version of this paper used a grid with about three nodes on the transition and fifteen quadrature nodes. On the corrected settings the calibrated point moves from $(\\kappa, \\sigma_m) = (10.0, 0.50)$ to $(10.75, 0.750)$, and with it every number in this section: the amplification factor falls from 3.6 to 2.47, the credit's effect on participation falls, and two conclusions reverse outright, the take-up incidence of Section 6.3 and the GDP-B sign below. The main result strengthened, since the distance from the coordination region grew, but that was luck rather than design. The full record of the checks, including Euler-equation errors and the invariance of the stationary distribution, is in the verification note in the public repository.",
 "It is worth being explicit about what the earlier footing got wrong and why, since the lesson is general. The asset grid ran to a wealth level the most patient calibration might reach while the French distribution ends near two years of income, so the whole distribution sat on six of two hundred nodes; a group's response to the belonging scale was therefore a step with a handful of levels, the integral of that step over the taste distribution needed thousands of nodes, and the participation cutoff fell among the same six nodes, so the aggregate rate could not settle under refinement at all. Rescaling the grid and smoothing the choice fixed both. The corrections then moved the calibration back along the curve of Section 5.2, from $(10.75, 0.750)$ to $(" + f"{KAPPA:.2f}, {SIGMA:.3f}" + ")$, which is within the numerical precision of the time the point the first draft of this paper had used; the intermediate draft, computed on the unresolved grid, had been pushed to the high-dispersion end of the curve where the fit is twice as poor and the map twice as flat, and every number that draft reported as a strengthening was a move along that curve rather than a finding. The full record, including Euler-equation errors and the invariance of the stationary distribution, is in the verification note in the public repository."),
]
tex = Path("paper/sage_sa.tex").read_text()
missing = [o for o,_ in edits if o not in tex]
print(f"{len(edits)} prose edits, {len(missing)} NOT FOUND")
for m in missing: print("   MISSING:", m[:110])
if "--apply" in sys.argv and not missing:
    for o,n in edits: tex = tex.replace(o,n,1)
    Path("paper/sage_sa.tex").write_text(tex); print("APPLIED")
