# Final comprehensive sweep of paper/sage_sa.tex against the final calibration
# (10.00, 0.510, theta=0.005, ne=80). Written after discovering that the
# earlier two generators (stage5_paper_subs.py, stage5_paper_prose.py) left
# gaps: the abstract, introduction, calibration paragraph, proposition
# subsection, omega table, and take-up narrative still carried stage-4 or
# intermediate numbers, and in two places (GDP-B sign, take-up disequalising
# claim) the surrounding PROSE LOGIC was now factually wrong, not just the
# numbers. This script fixes both.
import re, sys
from pathlib import Path

S = Path(__file__).parent
R = {}
for l in (S/"sa_level4_results.txt").read_text().splitlines():
    if "\t" in l and not l.startswith("#"):
        k, v = l.split("\t"); R[k] = float(v)

def pct(x): return 100*x
def f1(x): return f"{x:.1f}"
def f2(x): return f"{x:.2f}"
def f3(x): return f"{x:.3f}"

r0, lo, hi = R["r0"], R["r0_lo"], R["r0_hi"]
gap = hi - lo
ratio0 = hi/lo

# omega table, read fresh
om = {}
for l in (S/"sa_omega_l4.txt").read_text().splitlines():
    m = re.match(r"^0\.(\d+)\s+\|\s+([\d.]+)\s+\|\s+([\d.]+)\s+\|\s+([\d.]+)\s+\|\s+([\d.]+)\s*/\s*([\d.]+)\s+\|\s+([\d.]+)\s+\|\s+([\d.]+)\s+\|\s+([\d.]+)\s+\|\s+([\d.]+)", l)
    if m:
        w = float("0."+m.group(1))
        om[w] = dict(kappa=float(m.group(2)), sigma=float(m.group(3)), rate=float(m.group(4)),
                     lo=float(m.group(5)), hi=float(m.group(6)), slope=float(m.group(7)),
                     sigbar=float(m.group(8)), ratio=float(m.group(9)), frontier=float(m.group(10)))
for w in (0.15, 0.30, 0.50):
    assert w in om, f"omega {w} row not parsed"

edits = []

# ---------------------------------------------------------------- abstract --
old_abs = "At the French moments the bound is $0.47$ against the dispersion of $0.75$ the participation data require, so the calibrated economy sits some sixty percent outside the coordination region, and the model's own numerical boundary at $0.30$ confirms the ordering with room to spare. Three results follow. The education gradient in participation divides roughly two to one between the taste for belonging and agency operating through wealth, the income effect beating the price of time, which is why participation rises with income although richer households face a higher opportunity cost of time. A budget-balanced make-work-pay subsidy has a direct effect of four percentage points and an equilibrium effect of eleven, from 35 percent participation to 11, so outside the multiplicity region the complementarity still amplifies policy by a factor of 2.5, and that factor is the reciprocal of one minus the very map slope the bound constrains, which ties the policy result to the theorem rather than leaving it a separate simulation. And a participation tax credit, the analogue of France's charitable-donations deduction and the United Kingdom's Gift Aid, moves participation the other way and by more, at a sixth of the fiscal cost, so two policies from the same pro-work family swap places between a GDP ledger and a GDP-B ledger."
new_abs = (f"At the French moments the bound is ${f2(R['sigbar'])}$ against the dispersion of ${f3(R['sigma'])}$ the participation data require, so the calibrated economy sits about ten percent outside the coordination region, and the model's own numerical boundary at ${f2(R['frontier'])}$ confirms the ordering. Three results follow. The education gradient in participation divides roughly two to one between the taste for belonging and agency operating through wealth, the income effect beating the price of time, which is why participation rises with income although richer households face a higher opportunity cost of time. A budget-balanced make-work-pay subsidy has a direct effect of {f1(pct(r0-R['r_sub_direct']))} percentage points and an equilibrium effect of {f1(pct(r0-R['r_sub']))}, from {f1(pct(r0))} percent participation to {f1(pct(R['r_sub']))}, so at this margin the complementarity amplifies policy by a factor of {f1(R['amp'])} at the size of shock examined, against a small-shock prediction of {f1(1/(1-R['slope0']))} from the reciprocal of one minus the very map slope the bound constrains, which ties the policy result to the theorem rather than leaving it a separate simulation. And a participation tax credit, the analogue of France's charitable-donations deduction and the United Kingdom's Gift Aid, moves participation the other way and by more, at a fraction of the fiscal cost, and remains equalising across every take-up rate examined, so two policies from the same pro-work family swap places between a GDP ledger and a GDP-B ledger.")
edits.append((old_abs, new_abs))

# ------------------------------------------------------------- introduction --
old_i1 = "At the French moments the bound is $0.47$ while the participation data require $0.75$, so the economy sits some sixty percent outside the coordination region, and because the threshold version overstates the true slope the conclusion is conservative. Scanning the full model puts its actual boundary at $0.30$, comfortably inside the analytical bound, as it must be."
new_i1 = (f"At the French moments the bound is ${f2(R['sigbar'])}$ while the participation data require ${f3(R['sigma'])}$, so the economy sits about ten percent outside the coordination region, and because the threshold version overstates the true slope the conclusion is conservative. Scanning the full model puts its actual boundary at ${f2(R['frontier'])}$, inside the analytical bound, as it must be.")
edits.append((old_i1, new_i1))

old_i2 = "Third, the activation-policy result of the companion paper is amplified on the participation margin, and the amplification is not a free parameter. A budget-balanced 20 percent make-work-pay subsidy raises the return to market hours and taxes everyone a lump sum to pay for it; both push against the time commitment. The direct effect, holding everyone else's participation fixed, is a fall of four percentage points. The equilibrium effect is a fall of eleven, from 35 percent participation to 25: the social feedback multiplies the direct effect by two and a half, because each household's exit lowers the belonging return of every other household. The multiplier is $1/(1-G')$ at the equilibrium, so the same slope the bound of the first result constrains is the slope that sets the size of the second. A flat enough map to rule out coordination traps is a map that still amplifies policy by a factor near two and a half, and the two statements are one statement."
new_i2 = (f"Third, the activation-policy result of the companion paper is sharply amplified on the participation margin, and the amplification is not a free parameter. A budget-balanced 20 percent make-work-pay subsidy raises the return to market hours and taxes everyone a lump sum to pay for it; both push against the time commitment. The direct effect, holding everyone else's participation fixed, is a fall of {f1(pct(r0-R['r_sub_direct']))} percentage points. The equilibrium effect is a fall of {f1(pct(r0-R['r_sub']))}, from {f1(pct(r0))} percent participation to {f1(pct(R['r_sub']))}: the social feedback multiplies the direct effect by {f1(R['amp'])}, because each household's exit lowers the belonging return of every other household. The formula $1/(1-G')$ at the equilibrium slope predicts a multiplier of {f1(1/(1-R['slope0']))} for a small shock, so the same slope the bound of the first result constrains is the slope that sets the size of the second; the twenty-point shock examined is large enough that curvature pulls the realised multiplier below that linear prediction, and Section 6.1 reports both. A map flat enough to rule out coordination traps by only a modest margin is a map that can still amplify a large policy shock several times over, and the two statements are one statement read at two scales.")
edits.append((old_i2, new_i2))

old_i3 = "Fourth, the contrast that makes the policy point usable. Raising the lower-education group's agency to the population mean, an empowerment policy in the SAGE sense, raises equilibrium participation from 35 to 46 percent and narrows the education gap, without any fiscal instrument at all. A participation tax credit, modelled at the real rebate rates of the United Kingdom's Gift Aid and France's charitable-donations deduction, does the same from the other direction and far more cheaply: Gift Aid's 25 percent rebate lifts participation from 35 to 85 percent at a sixth of the work subsidy's fiscal cost. Because such credits are claimed unevenly, I add a take-up gradient, and it turns the distributional verdict. At full take-up the credit is equalising, cutting the ratio of higher- to lower-group participation from 1.65 to 1.14; at half take-up it is roughly neutral; and when the lower group claims at only a quarter of the higher group's rate the ratio rises to 1.50, so the instrument becomes disequalising while remaining expansionary. Take-up is therefore not a second-order caveat on this policy but the thing that decides who it is for. Policies from the same pro-work family therefore have opposite effects on the social fabric: subsidising hours raises the price of time and unravels participation, while empowering people or paying them for the act of joining crowds it in. An evaluation framework that does not carry the social dimension cannot tell these policies apart on the margin where they differ most."
new_i3 = (f"Fourth, the contrast that makes the policy point usable. Raising the lower-education group's agency to the population mean, an empowerment policy in the SAGE sense, raises equilibrium participation from {f1(pct(r0))} to {f1(pct(R['r_emp']))} percent and narrows the education gap, without any fiscal instrument at all. A participation tax credit, modelled at the real rebate rates of the United Kingdom's Gift Aid and France's charitable-donations deduction, does the same from the other direction and far more cheaply: Gift Aid's 25 percent rebate lifts participation from {f1(pct(r0))} to {f1(pct(R['cred_25_100_r']))} percent at a fraction of the work subsidy's fiscal cost. Because such credits are claimed unevenly, I add a take-up gradient, and the natural worry does not materialise: the credit stays equalising at every take-up rate examined. The ratio of higher- to lower-group participation is {f2(ratio0)} at baseline; full take-up cuts it to {f2(R['cred_25_100_hi']/R['cred_25_100_lo'])}, and even at a quarter take-up, where the lower group claims the rebate at only a fraction of the higher group's rate, it falls to {f2(R['cred_25_25_hi']/R['cred_25_25_lo'])}, still below baseline. Take-up disciplines how much the credit equalises, not whether it does. Policies from the same pro-work family therefore have opposite effects on the social fabric: subsidising hours raises the price of time and unravels participation, while empowering people or paying them for the act of joining crowds it in. An evaluation framework that does not carry the social dimension cannot tell these policies apart on the margin where they differ most.")
edits.append((old_i3, new_i3))

# ------------------------------------------------------------- calibration --
old_cal = "I calibrate $(\\kappa, \\sigma_m)$ to the two INSEE participation moments, group rates of 0.25 and 0.45 at a stable equilibrium, with $\\omega = 0.30$ held at its central value and swept in robustness. The best fit is $\\kappa = 10.75$, $\\sigma_m = 0.750$, at which the economy has a unique stable equilibrium with aggregate participation 0.353 and group rates 0.267 and 0.439 (Figure \\ref{fig:gradient})."
new_cal = (f"I calibrate $(\\kappa, \\sigma_m)$ to the two INSEE participation moments, group rates of 0.25 and 0.45 at a stable equilibrium, with $\\omega = 0.30$ held at its central value and swept in robustness. The best fit is $\\kappa = {f2(R['kappa'])}$, $\\sigma_m = {f3(R['sigma'])}$, at which the economy has a unique stable equilibrium with aggregate participation {f3(r0)} and group rates {f3(lo)} and {f3(hi)} (Figure \\ref{{fig:gradient}}).")
edits.append((old_cal, new_cal))

# ------------------------------------------------------------- proposition --
old_prop = "At the calibrated equilibrium the aggregate rate is $r = 0.353$, group rates are $0.267$ and $0.439$, and $\\omega = 0.30$. The complementarity factor is $1.280$ and the density term $0.361$, so $\\bar\\sigma = 0.463$. The dispersion the participation data require is $\\sigma_m = 0.750$, which exceeds the bound by sixty percent. Multiplicity is ruled out, and not marginally: the economy would need its belonging tastes compressed by well over a third before coordination traps became possible at all."
new_prop = (f"At the calibrated equilibrium the aggregate rate is $r = {f3(r0)}$, group rates are ${f3(lo)}$ and ${f3(hi)}$, and $\\omega = 0.30$. The complementarity factor is ${f3(R['comp'])}$ and the density term ${f3(R['dens'])}$, so $\\bar\\sigma = {f3(R['sigbar'])}$. The dispersion the participation data require is $\\sigma_m = {f3(R['sigma'])}$, which exceeds the bound by about ten percent. Multiplicity is ruled out, though not by a wide margin: the economy would need its belonging tastes compressed by roughly a tenth before coordination traps became possible at all, which is why Section 5.3 checks how robust that margin is to the one parameter the data do not pin down.")
edits.append((old_prop, new_prop))

# ------------------------------------------------------------ omega table ---
old_tab = "0.15 & 13.00 & 0.740 & 0.284 / 0.402 & 0.932 & 0.699 & 1.06 \\\\\n0.30 & 10.75 & 0.740 & 0.299 / 0.417 & 0.626 & 0.469 & 1.58 \\\\\n0.50 & 8.00 & 0.410 & 0.233 / 0.434 & 0.615 & 0.262 & 1.56 \\\\"
def row(w):
    d = om[w]
    return f"{w:.2f} & {d['kappa']:.2f} & {d['sigma']:.3f} & {d['lo']:.3f} / {d['hi']:.3f} & {d['slope']:.3f} & {d['sigbar']:.3f} & {d['ratio']:.2f} \\\\"
new_tab = "\n".join(row(w) for w in (0.15, 0.30, 0.50))
edits.append((old_tab, new_tab))

old_omega_p1 = "Three things follow, and the second is a caution rather than a comfort. First, the verdict is robust: the ratio exceeds one at every $\\omega$, so multiplicity is ruled out however the private share is set, and the direct numerical scan agrees, putting the fold at $\\sigma_m \\le 0.68$, $0.30$ and $0.16$ respectively, always inside the bound.\n\nSecond, the margin is not robust. At $\\omega = 0.15$ the ratio is 1.06 and the map slope is 0.932, so the economy sits barely outside the coordination region and close to a fold. A reader who believes participation is almost entirely a social payoff should read this paper as saying France is near the edge, not far from it. That is the honest statement of what the result depends on, and it identifies $\\omega$ as the quantity worth measuring next: the difference between a slope of 0.62 and one of 0.93 is the difference between a policy multiplier of two and a half and one of fifteen, which matters far more for policy than the multiplicity verdict does."
new_omega_p1 = (
 f"Three things follow, and none of them is a comfort. First, the verdict is robust: the ratio exceeds one at every $\\omega$ examined, so multiplicity is ruled out however the private share is set, and the direct numerical scan agrees, putting the fold at $\\sigma_m \\le {om[0.15]['frontier']:.2f}$, ${om[0.30]['frontier']:.2f}$ and ${om[0.50]['frontier']:.2f}$ respectively, always inside the bound.\n\n"
 f"Second, the margin is thin across most of the range examined, and the central calibration is one of the thin points. At $\\omega = 0.15$ the ratio is {om[0.15]['ratio']:.2f} with map slope {om[0.15]['slope']:.3f}; at the central $\\omega = 0.30$ the ratio is {om[0.30]['ratio']:.2f} with slope {om[0.30]['slope']:.3f}, essentially the same margin. Only at $\\omega = 0.50$ does the economy move comfortably away from the edge, ratio {om[0.50]['ratio']:.2f} and slope {om[0.50]['slope']:.3f}. A reader who believes participation is anywhere below about half a private payoff should read this paper as saying France sits close to the coordination boundary, not far from it. That is the honest statement of what the result depends on, and it identifies $\\omega$ as the quantity worth measuring next: the difference between a slope of {om[0.50]['slope']:.2f} and one of {om[0.30]['slope']:.2f} is the difference between a policy multiplier of {1/(1-om[0.50]['slope']):.1f} and one of {1/(1-om[0.30]['slope']):.0f}, which matters far more for policy than the multiplicity verdict does."
)
edits.append((old_omega_p1, new_omega_p1))

old_omega_p2 = "Third, the fit improves markedly at the high private share. At $\\omega = 0.50$ the calibrated group rates are 0.233 and 0.434 against targets of 0.25 and 0.45, so the gradient shortfall reported in Section 3 is a consequence of holding $\\omega$ at 0.30 rather than a structural limit of the two-cell model. The verdict at that better-fitting point is the same, ratio 1.56 against 1.58, and so is the map slope, so nothing in Section 6 turns on the choice between these two; what the comparison buys is the knowledge that the model can hit the gradient, not a different answer. Table \\ref{tab:omega}'s middle row also serves as a check on the calibration procedure itself, since it repeats the headline calibration through a coarser search and returns $\\kappa^* = 10.75$ and $\\sigma_m^* = 0.740$ against the headline $0.750$."
new_omega_p2 = (f"Third, the fit at the central calibration is already close: group rates {f3(lo)} and {f3(hi)} against targets of 0.25 and 0.45, so the gradient shortfall is modest rather than structural. Fit does not improve monotonically with $\\omega$ in this sweep; what moves is the margin, and Section 6 states the policy magnitudes with that dependence in view rather than treating $\\omega = 0.30$ as settled.")
edits.append((old_omega_p2, new_omega_p2))

# --------------------------------------------------------------- captions --
old_c1 = "The subsidy shifts the whole response down and the equilibrium slides from 35 to 25 percent; the credit shifts it up and the equilibrium rises to 66.}"
new_c1 = f"The subsidy shifts the whole response down and the equilibrium slides from {f1(pct(r0))} to {f1(pct(R['r_sub']))} percent; the credit shifts it up and the equilibrium rises to {f1(pct(R['cred_25_100_r']))}.}}"
edits.append((old_c1, new_c1))

old_c2 = "The social feedback multiplies the subsidy's 4.3-point direct effect into a 10.6-point fall, a factor of 2.47 against the $1/(1-G')$ prediction of 2.62.}"
new_c2 = f"The social feedback multiplies the subsidy's {f1(pct(r0-R['r_sub_direct']))}-point direct effect into a {f1(pct(r0-R['r_sub']))}-point fall, a factor of {f1(R['amp'])}, against a small-shock prediction of {f1(1/(1-R['slope0']))} from $1/(1-G')$; the gap between the two is curvature at the size of shock examined, quantified in Section 6.1.}}"
edits.append((old_c2, new_c2))

old_c3 = "The work subsidy costs a fifth of mean labour income and lowers participation to 25 percent. Gift Aid's 25 percent rebate, the central credit case, costs a thirtieth and raises participation by 31 points with both groups interior; the France-style 66 percent rate costs about an eighth and takes the model close to saturation, so it is shown as an upper bound."
new_c3 = f"The work subsidy costs about a fifth of mean labour income and lowers participation to {f1(pct(R['r_sub']))} percent. Gift Aid's 25 percent rebate, the central credit case, costs about a tenth and raises participation by {f1(pct(R['cred_25_100_r']-r0))} points with both groups interior; the France-style 66 percent rate costs about three tenths and takes the model close to saturation, so it is shown as an upper bound."
edits.append((old_c3, new_c3))

# ---------------------------------------------------------------- 6.1 text --
old_61 = "mean labour income rises by 6.6 percent here, and consumption by 5.6 percent in the companion paper's version of the same experiment"
new_61 = f"mean labour income rises by {f1(R['gdp_work_subsidy_(20%)'])} percent here, and consumption by 5.6 percent in the companion paper's version of the same experiment"
edits.append((old_61, new_61))

# ------------------------------------------------------------- take-up 6.3 --
old_tu = "Two things come out of the exercise. The first is that take-up decides the distributional sign, and the natural worry about these credits is correct. The ratio of higher- to lower-group participation is 1.40 at baseline. Claimed evenly, the credit compresses it to 1.19 at the Gift Aid rate and to 1.04 at the French rate: participation is a bounded quantity and the group with more room to move gains more, so a rebate everyone claims is equalising. Claimed unevenly, the arithmetic reverses. At half take-up the Gift Aid credit is distributionally neutral, 1.43 against 1.40, and at quarter take-up it is disequalising, 1.60; the French rate goes further, to 1.72, because the higher group is near saturation and absorbs the whole of the throttled inflow. The complementarity is what does it: the higher group's induced entry raises the belonging return for everyone, so the lower group is partly carried along, but not enough to offset a rebate it does not claim. A credit designed to build the social fabric can widen the participation gap it was meant to close, and whether it does turns on an implementation detail rather than on the rebate rate.\n\nSecond, and unaffected by the first, take-up disciplines the level without touching the aggregate sign. Gift Aid's aggregate falls from 66 to 56 percent as take-up drops to a quarter, and its cost falls from 3.2 to 2.0 percent of mean income, so the policy stays expansionary and stays cheap relative to the work subsidy throughout. The policy conclusion is therefore conditional in a way the earlier draft's was not: as an instrument for raising participation the credit dominates the work subsidy at every take-up rate examined, and as an instrument for narrowing the education gap it works only if it is claimed evenly."
new_tu = (
 f"Two things come out of the exercise, and the natural worry about these credits does not materialise here. The ratio of higher- to lower-group participation is {f2(ratio0)} at baseline. Claimed evenly, the credit compresses it to {f2(R['cred_25_100_hi']/R['cred_25_100_lo'])} at the Gift Aid rate and to {f2(R['cred_66_100_hi']/R['cred_66_100_lo'])} at the French rate: participation is a bounded quantity and the group with more room to move gains more, so a rebate everyone claims is equalising. Claimed unevenly, the credit equalises less but does not reverse: at half take-up the Gift Aid ratio is {f2(R['cred_25_50_hi']/R['cred_25_50_lo'])}, and at a quarter take-up it is {f2(R['cred_25_25_hi']/R['cred_25_25_lo'])}, still below the {f2(ratio0)} baseline; the French rate follows the same pattern, {f2(R['cred_66_50_hi']/R['cred_66_50_lo'])} at half take-up and {f2(R['cred_66_25_hi']/R['cred_66_25_lo'])} at a quarter. The complementarity is why it stays equalising even when claimed unevenly: the higher group's induced entry raises the belonging return for everyone, so the lower group is partly carried along by a rebate it does not itself claim.\n\n"
 f"Second, take-up disciplines the level without touching the sign or the ranking. Gift Aid's aggregate falls from {f1(pct(R['cred_25_100_r']))} to {f1(pct(R['cred_25_25_r']))} percent as take-up drops to a quarter, and its cost falls from {f1(R['cred_25_100_cost'])} to {f1(R['cred_25_25_cost'])} percent of mean income, so the policy stays expansionary and stays cheap relative to the work subsidy throughout. As an instrument for raising participation the credit dominates the work subsidy at every take-up rate examined; as an instrument for narrowing the education gap it does the same at every take-up rate examined, though less effectively as take-up becomes more uneven."
)
edits.append((old_tu, new_tu))

# ----------------------------------------------------------- GDP-B ledger --
old_gtab = "baseline & 0.353 & --- & --- \\\\\nwork subsidy (20\\%) & 0.113 & $+6.6\\%$ & $+-1.2\\%$ \\\\\nempowerment & 0.465 & $+2.2\\%$ & $+5.3\\%$ \\\\\nparticipation credit (25\\%) & 0.849 & $-4.7\\%$ & $+10.5\\%$ \\\\\nparticipation credit (66\\%) & 0.995 & $-6.2\\%$ & $+13.5\\%$ \\\\"
new_gtab = (
 f"baseline & {f3(r0)} & --- & --- \\\\\n"
 f"work subsidy (20\\%) & {f3(R['r_sub'])} & $+{f1(R['gdp_work_subsidy_(20%)'])}\\%$ & ${f1(R['gdpb_work_subsidy_(20%)'])}\\%$ \\\\\n"
 f"empowerment & {f3(R['r_emp'])} & $+{f1(R['gdp_empowerment'])}\\%$ & $+{f1(R['gdpb_empowerment'])}\\%$ \\\\\n"
 f"participation credit (25\\%) & {f3(R['cred_25_100_r'])} & ${f1(R['gdp_participation_credit_(25%)'])}\\%$ & $+{f1(R['gdpb_participation_credit_(25%)'])}\\%$ \\\\\n"
 f"participation credit (66\\%) & {f3(R['cred_66_100_r'])} & ${f1(R['gdp_participation_credit_(66%)'])}\\%$ & $+{f1(R['gdpb_participation_credit_(66%)'])}\\%$ \\\\"
)
edits.append((old_gtab, new_gtab))

old_gp1 = "The two ledgers rank the two fiscal policies in opposite orders. On material GDP the work subsidy wins outright, $+6.6$ percent against the Gift Aid credit's $-4.7$, since participation takes time that would otherwise be worked. On GDP-B the ranking inverts, $+-1.2$ against $+10.5$, and the France-rate credit widens the gap to $+13.5$. Empowerment raises both columns and costs nothing. A planner choosing on the first column picks the work subsidy; a planner choosing on the second picks the credit; and the two planners are looking at the same model, the same households and the same fiscal envelope (Figure \\ref{fig:gdpb})."
new_gp1 = (f"The two ledgers rank the two fiscal policies in opposite orders. On material GDP the work subsidy wins outright, $+{f1(R['gdp_work_subsidy_(20%)'])}$ percent against the Gift Aid credit's ${f1(R['gdp_participation_credit_(25%)'])}$, since participation takes time that would otherwise be worked. On GDP-B the ranking inverts: the subsidy is negative, ${f1(R['gdpb_work_subsidy_(20%)'])}$ percent, against the credit's $+{f1(R['gdpb_participation_credit_(25%)'])}$, and the France-rate credit widens the gap to $+{f1(R['gdpb_participation_credit_(66%)'])}$. Empowerment raises both columns and costs nothing. A planner choosing on the first column picks the work subsidy; a planner choosing on the second picks the credit, and at this calibration that second planner is not merely picking a smaller gain, since the subsidy actually lowers GDP-B (Figure \\ref{{fig:gdpb}}).")
edits.append((old_gp1, new_gp1))

old_gp2 = "The honest qualification is that the reversal here is one of ranking rather than of sign. At the model's own shadow price the work subsidy still raises GDP-B, by -1.2 percent: the fabric it destroys is worth less than the output it manufactures. It becomes GDP-B reducing only if a fully participating society's cohesion is worth more than 27 percent of GDP, where the model's own price is 33. An earlier draft of this paper reported the stronger claim, that the subsidy lowers GDP-B outright, and that claim was an artefact of the coarse numerical settings this version replaces. Which of the two statements is right in the world is not something this model can settle, because it turns entirely on the price of the fabric, which is exactly the quantity the WELLBY literature exists to estimate \\citep{layard2023}. That is the useful form of the result: the model supplies the quantities and the breakeven price, 27 percent of GDP per unit of participation, and the wellbeing-valuation literature supplies the number that decides the sign. What the model does settle on its own is the ranking, which does not depend on the price at all once the price is positive, since the credit dominates the subsidy on participation and the two differ by less than four points of GDP."
new_gp2 = (f"At the model's own shadow price the work subsidy lowers GDP-B, by {abs(R['gdpb_work_subsidy_(20%)']):.1f} percent: the fabric it destroys is worth more than the output it manufactures. That sign depends on the price, since the breakeven at which the two exactly offset is {f1(R['pi_star_pct'])} percent of GDP per unit of participation against the model's own {f1(R['pi_model_pct'])}, so the two are close and a reader who prices the fabric a little lower would find the subsidy GDP-B neutral rather than reducing. Which valuation is right in the world is not something this model can settle on its own, because it turns entirely on the price of the fabric, which is exactly the quantity the WELLBY literature exists to estimate \\citep{{layard2023}}. That is the useful form of the result: the model supplies the quantities and the breakeven price, and the wellbeing-valuation literature supplies the number that fixes how far from that breakeven the true price sits. What the model does settle on its own is the ranking, which does not depend on the price at all once the price is positive, since the credit dominates the subsidy on participation.")
edits.append((old_gp2, new_gp2))

# ----------------------------------------------------------------- 5.3 sec --
old_53 = "Third, the distance matters as much as the verdict, and it is a distance rather than a hair's breadth: the taste distribution would have to be compressed from a log standard deviation of $0.750$ to below $0.463$ on the analytical bound, or below $0.40$ on the model's own scan, before coordination traps became possible."
new_53 = (f"Third, the distance is modest, and stating it plainly is more useful than rounding it up: the taste distribution would have to be compressed from a log standard deviation of ${f3(R['sigma'])}$ to below ${f3(R['sigbar'])}$ on the analytical bound, or below ${f2(R['frontier'])}$ on the model's own scan, before coordination traps became possible, and Section 5.3 shows that margin narrows further at lower values of the private share $\\omega$.")
edits.append((old_53, new_53))

# --------------------------------------------------------------- conclusion --
old_con1 = "The paper's central result is a bound. In a discrete-choice model of social participation with lognormal tastes, multiple equilibria require taste dispersion below a threshold built from observed participation rates and one preference share, and that threshold tightens as the participation gradient steepens. Coordination traps and visible gradients are substitutes, and the data can be asked which it has. Asked of France, it answers gradients: the economy sits some sixty percent outside the coordination region on the analytical bound, and further still on the model's own numerical scan, which puts the fold at a dispersion of 0.40 against the 0.75 the data require. That is the verdict at the central private share, and the verdict itself holds at every private share examined; the margin behind it does not, which is why the private share is the quantity this framework most wants measured next. The result needs no structural estimation, so it travels to any setting where participation rates by group are known, which is most of them."
new_con1 = (f"The paper's central result is a bound. In a discrete-choice model of social participation with lognormal tastes, multiple equilibria require taste dispersion below a threshold built from observed participation rates and one preference share, and that threshold tightens as the participation gradient steepens. Coordination traps and visible gradients are substitutes, and the data can be asked which it has. Asked of France, it answers gradients, though not by a wide margin: the economy sits about ten percent outside the coordination region on the analytical bound, and a little further on the model's own numerical scan, which puts the fold at a dispersion of {f2(R['frontier'])} against the {f3(R['sigma'])} the data require. That is the verdict at the central private share, and the verdict itself holds at every private share examined between 0.15 and 0.50; the margin behind it varies substantially across that range and is thin at the low end, which is why the private share is the quantity this framework most wants measured next. The result needs no structural estimation, so it travels to any setting where participation rates by group are known, which is most of them.")
edits.append((old_con1, new_con1))

old_con2 = "The bound then does a second job, which is the part I did not anticipate when I set out to prove it. The slope it constrains is the same slope that sets the equilibrium multiplier on any policy, $1/(1-G')$, so a model disciplined by participation rates is a model whose amplification factor is no longer free. Here that factor is about two and a half: a financed work subsidy's 4.3-point direct effect becomes an 11-point fall, an empowerment policy that closes the agency gap moves participation by 2.5 points without a fiscal instrument, and a participation tax credit at Gift Aid's real rebate rate moves it by 31 points in the opposite direction at a sixth of the subsidy's fiscal cost. The same calibrated complementarity does all three pieces of arithmetic, and the theorem says why it must."
new_con2 = (f"The bound then does a second job, which is the part I did not anticipate when I set out to prove it. The slope it constrains is the same slope that sets the equilibrium multiplier on any policy, $1/(1-G')$, so a model disciplined by participation rates is a model whose amplification factor is no longer free; at this calibration the linear prediction is a factor of {f1(1/(1-R['slope0']))}, though the multiplier realised on the twenty-point shock examined is smaller once curvature is accounted for, {f1(R['amp'])}. A financed work subsidy's {f1(pct(r0-R['r_sub_direct']))}-point direct effect becomes a {f1(pct(r0-R['r_sub']))}-point fall, an empowerment policy that closes the agency gap moves participation by {f1(pct(R['r_emp']-r0))} points without a fiscal instrument, and a participation tax credit at Gift Aid's real rebate rate moves it by {f1(pct(R['cred_25_100_r']-r0))} points in the opposite direction at a fraction of the subsidy's fiscal cost. The same calibrated complementarity does all three pieces of arithmetic, and the theorem says why it must.")
edits.append((old_con2, new_con2))

old_con3 = "The policy conclusions are correspondingly conditional. A credit that pays for the act of joining outperforms a subsidy that pays for hours, on participation and on the inclusive ledger, at every take-up rate examined. Whether it also narrows the education gap depends on take-up, and at a quarter take-up it widens it. Whether the work subsidy is inclusive-output reducing rather than merely inclusive-output inferior depends on a price this model cannot supply: the fabric would have to be worth more than 27 percent of GDP, against the model's own 33 percent. Both are places where the framework hands a specific, answerable question to the wellbeing-measurement literature rather than answering it by assumption."
new_con3 = (f"The policy conclusions are correspondingly direct. A credit that pays for the act of joining outperforms a subsidy that pays for hours, on participation and on the inclusive ledger, at every take-up rate examined, and it narrows the education gap at every take-up rate examined too, though less so the more unevenly it is claimed. At the model's own price of the fabric, {f1(R['pi_model_pct'])} percent of GDP, the work subsidy is inclusive-output reducing rather than merely inclusive-output inferior, since that price exceeds the {f1(R['pi_star_pct'])} percent breakeven; a reader who values the fabric a little below the model's own estimate would find the subsidy merely GDP-B neutral. This is a place where the framework hands a specific, answerable question, the money value of participation, to the wellbeing-measurement literature rather than answering it by assumption.")
edits.append((old_con3, new_con3))

if __name__ == "__main__":
    tex = Path("paper/sage_sa.tex").read_text()
    missing = [o for o,_ in edits if o not in tex]
    changed = sum(1 for o,n in edits if o != n)
    print(f"{len(edits)} edits, {changed} change text, {len(missing)} NOT FOUND")
    for m in missing:
        print("   MISSING:", m[:140])
    if "--apply" in sys.argv and not missing:
        for o,n in edits: tex = tex.replace(o, n, 1)
        Path("paper/sage_sa.tex").write_text(tex)
        print("APPLIED")
