# Prose edits for paper/sage_sa.tex that the stage 5 core requires: the model
# now carries an i.i.d. logit taste shock, the proposition is its theta -> 0
# limit, and the numerics paragraphs describe the new footing. Dry-run unless
# --apply. Run AFTER stage5_paper_subs.py.
import sys
from pathlib import Path
edits = [
# Section 2.3: the reduction paragraph gains the shock
("Computation exploits a reduction: within a group, the payoff depends on $(\\kappa, m, B_g, \\omega, r)$ only through one scalar, so each group's response is precomputed once on a grid of that scalar at production resolution, and every map evaluation, calibration loop, and policy counterfactual is interpolation.",
 "One more ingredient is needed before the model can be computed reliably, and it is the one \\citet{brock2001} start from: on top of the persistent taste $m$, each period the household draws an i.i.d. type-1 extreme-value shock to the participation payoff, with scale $\\theta$. The participation choice is then a logit probability rather than a step, and the hard-threshold model of the previous subsection is its $\\theta \\to 0$ limit. The shock is kept small, $\\theta = 0.01$, and Section 6.5 shows that every quantity reported has settled to within a fraction of a point of that limit; its role is to make the aggregate an integral of a smooth function over the wealth distribution rather than the mass above a cutoff, which is what the discretisation could not otherwise resolve. Computation then exploits a reduction: within a group, the payoff depends on $(\\kappa, m, B_g, \\omega, r)$ only through one scalar, so each group's response is precomputed once on a grid of that scalar at production resolution, and every map evaluation, calibration loop, and policy counterfactual is interpolation."),
# Section 3: numerical settings paragraph
("The response families are built on a grid concentrated at spacing $0.2$ across the transition interval, and the taste quadrature uses 2000 nodes; at those settings the calibrated equilibrium moves by 0.002 between 500 and 4000 nodes.",
 "The response families are built on a grid concentrated at spacing $0.2$ across the transition interval; the taste quadrature uses 2000 nodes, of which 500 would suffice once the choice is smoothed; and the asset grid is concentrated where the wealth distribution actually lives, which for the French calibration is below two years of income. At those settings the calibrated equilibrium is stable to $3 \\times 10^{-4}$ across a fourfold range of asset-grid sizes."),
# Section 5: after the proposition's proof paragraph, one sentence on the limit
("The proposition says something that is not evident before the algebra:",
 "The proposition is stated for the hard-threshold model, and the computed model of Section 2.3 carries a small logit shock; the two agree in the limit, and at the $\\theta$ used the map slope sits within 0.002 of its limiting value, so nothing below turns on the distinction. The proposition says something that is not evident before the algebra:"),
# Section 6.5: full rewrite
("The companion paper's central quantity, the public good $Q = \\mathbb{E}[1-e]$, is a mean of effort and inherits the resolution of the effort grid, which is why that paper reports the checks it does. The central quantity here is different: participation is a discrete choice, and the aggregate rate is a mass rather than an average of a finely graded object, so it should be far less sensitive. It is. Rebuilding the response families with the effort grid doubled and doubled again, the calibrated equilibrium moves from 0.35303 to 0.35305 to 0.35307 and the group rates move in the fifth decimal; mean labour income, which does inherit the effort grid, moves by at most three tenths of a percent, which is the accuracy to attach to the GDP column of Table \\ref{tab:gdpb}.",
 "Three checks carry the numbers in this paper, and each exists because something was once reported wrong. The first is an identity. For a small financed subsidy the equilibrium response must equal the direct response divided by $1 - G'(r^*)$, with no free parameter, so a numerical footing that fails it is wrong whatever else it reproduces. At a one percent subsidy the measured multiplier is 2.584 against a predicted 2.586, a gap of a tenth of a percent, and the gap grows with the shock exactly as curvature says it should; the earlier footing of this paper missed the same test by 48 percent. The second is grid convergence. The participation rate is stable to $3 \\times 10^{-4}$ across asset grids from 100 to 400 nodes, to the sixth decimal across the grid on which the aggregate map is traced, and to the fifth decimal across two doublings of the effort grid; mean labour income, which inherits the effort grid, moves by at most three tenths of a percent, which is the accuracy to attach to the GDP column of Table \\ref{tab:gdpb}. The third is the limit in $\\theta$. Sending the logit scale from 0.02 to 0.0025, the participation rate moves 0.371, 0.364, 0.361, 0.361 and the map slope 0.607, 0.614, 0.615, 0.616, so at the working value both sit within 0.004 and 0.002 of the hard-threshold limit the proposition is stated for."),
("The sensitivity that does matter here is the one Section 3 describes, and it is worth being explicit about how much it cost. The response of a group to the belonging scale is close to a step function, so a grid spread evenly over the range puts almost no nodes where the response moves, and the integral of a near-step over the taste distribution converges slowly. An earlier version of this paper used a grid with about three nodes on the transition and fifteen quadrature nodes. On the corrected settings the calibrated point moves from $(\\kappa, \\sigma_m) = (10.0, 0.50)$ to $(10.75, 0.750)$, and with it every number in this section: the amplification factor falls from 3.6 to 2.47, the credit's effect on participation falls, and two conclusions reverse outright, the take-up incidence of Section 6.3 and the GDP-B sign below. The main result strengthened, since the distance from the coordination region grew, but that was luck rather than design. The full record of the checks, including Euler-equation errors and the invariance of the stationary distribution, is in the verification note in the public repository.",
 "It is worth being explicit about what the earlier footing got wrong and why, since the lesson is general. The asset grid ran to a wealth level the most patient calibration might reach while the French distribution ends near two years of income, so the whole distribution sat on six of two hundred nodes; a group's response to the belonging scale was therefore a step with a handful of levels, the integral of that step over the taste distribution needed thousands of nodes, and the participation cutoff fell among the same six nodes, so the aggregate rate could not settle under refinement at all. Rescaling the grid and smoothing the choice fixed both. Relative to the version computed before those corrections, the levels moved by about one point and every conclusion held to within a percent: the ratio $\\sigma^*_m/\\bar\\sigma$ from 1.598 to 1.604, the multiplier from 2.47 to 2.47, the take-up ratios from 1.19, 1.43, 1.60 to 1.19, 1.42, 1.56. Relative to the version before that, which used a grid with three nodes on the transition and fifteen quadrature nodes, the calibrated point had moved from $(\\kappa, \\sigma_m) = (10.0, 0.50)$ to $(10.75, 0.750)$ and two conclusions had reversed, the take-up incidence of Section 6.3 and the GDP-B sign below. The full record, including Euler-equation errors and the invariance of the stationary distribution, is in the verification note in the public repository."),
]
tex = Path("paper/sage_sa.tex").read_text()
missing = [o for o,_ in edits if o not in tex]
print(f"{len(edits)} prose edits, {len(missing)} NOT FOUND")
for m in missing: print("   MISSING:", m[:110])
if "--apply" in sys.argv and not missing:
    for o,n in edits: tex = tex.replace(o,n,1)
    Path("paper/sage_sa.tex").write_text(tex); print("APPLIED")
